name: RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download and Setup ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok.exe authtoken YOUR_AUTH_TOKEN

      - name: Enable RDP and Add User
        run: |
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start ngrok Tunnel
        run: |
          Start-Process -FilePath .\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 20

      - name: Show RDP Address
        run: |
          $tunnel = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
          $rdp = $tunnel.tunnels[0].public_url
          echo "🌐 عنوان RDP الخاص بك:"
          echo $rdp
